# Generated by Django 4.2.1 on 2023-05-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_preparation_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_dteps_is_html',
            new_name='preparation_steps_is_html',
        ),
    ]
